// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: homectl.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceActionType int32

const (
	ServiceActionType_SERVICE_ACTION_UNSPECIFIED ServiceActionType = 0
	ServiceActionType_SERVICE_ACTION_START       ServiceActionType = 1
	ServiceActionType_SERVICE_ACTION_STOP        ServiceActionType = 2
	ServiceActionType_SERVICE_ACTION_RESTART     ServiceActionType = 3
	ServiceActionType_SERVICE_ACTION_ENABLE      ServiceActionType = 4
	ServiceActionType_SERVICE_ACTION_DISABLE     ServiceActionType = 5
)

// Enum value maps for ServiceActionType.
var (
	ServiceActionType_name = map[int32]string{
		0: "SERVICE_ACTION_UNSPECIFIED",
		1: "SERVICE_ACTION_START",
		2: "SERVICE_ACTION_STOP",
		3: "SERVICE_ACTION_RESTART",
		4: "SERVICE_ACTION_ENABLE",
		5: "SERVICE_ACTION_DISABLE",
	}
	ServiceActionType_value = map[string]int32{
		"SERVICE_ACTION_UNSPECIFIED": 0,
		"SERVICE_ACTION_START":       1,
		"SERVICE_ACTION_STOP":        2,
		"SERVICE_ACTION_RESTART":     3,
		"SERVICE_ACTION_ENABLE":      4,
		"SERVICE_ACTION_DISABLE":     5,
	}
)

func (x ServiceActionType) Enum() *ServiceActionType {
	p := new(ServiceActionType)
	*p = x
	return p
}

func (x ServiceActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_homectl_proto_enumTypes[0].Descriptor()
}

func (ServiceActionType) Type() protoreflect.EnumType {
	return &file_homectl_proto_enumTypes[0]
}

func (x ServiceActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceActionType.Descriptor instead.
func (ServiceActionType) EnumDescriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{0}
}

type FingerprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerprintRequest) Reset() {
	*x = FingerprintRequest{}
	mi := &file_homectl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintRequest) ProtoMessage() {}

func (x *FingerprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintRequest.ProtoReflect.Descriptor instead.
func (*FingerprintRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{0}
}

type FingerprintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fingerprint   string                 `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FingerprintResponse) Reset() {
	*x = FingerprintResponse{}
	mi := &file_homectl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintResponse) ProtoMessage() {}

func (x *FingerprintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintResponse.ProtoReflect.Descriptor instead.
func (*FingerprintResponse) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{1}
}

func (x *FingerprintResponse) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

type PairRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable label for the pairing client (e.g. its hostname),
	// recorded alongside the pinned fingerprint for the operator's reference.
	ClientName    string `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_homectl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{2}
}

func (x *PairRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type PairResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accepted          bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	DaemonFingerprint string                 `protobuf:"bytes,2,opt,name=daemon_fingerprint,json=daemonFingerprint,proto3" json:"daemon_fingerprint,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_homectl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{3}
}

func (x *PairResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PairResponse) GetDaemonFingerprint() string {
	if x != nil {
		return x.DaemonFingerprint
	}
	return ""
}

func (x *PairResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_homectl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{4}
}

type SystemInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os              string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	PlatformVersion string                 `protobuf:"bytes,3,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	UptimeSeconds   uint64                 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuModel        string                 `protobuf:"bytes,5,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCores        uint32                 `protobuf:"varint,6,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsagePercent float64                `protobuf:"fixed64,7,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemTotalBytes   uint64                 `protobuf:"varint,8,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	MemUsedBytes    uint64                 `protobuf:"varint,9,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	DiskTotalBytes  uint64                 `protobuf:"varint,10,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes   uint64                 `protobuf:"varint,11,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_homectl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{5}
}

func (x *SystemInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SystemInfoResponse) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *SystemInfoResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemInfoResponse) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *SystemInfoResponse) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *SystemInfoResponse) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *SystemInfoResponse) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *SystemInfoResponse) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *SystemInfoResponse) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *SystemInfoResponse) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

type StartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,3,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCommand) Reset() {
	*x = StartCommand{}
	mi := &file_homectl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCommand) ProtoMessage() {}

func (x *StartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCommand.ProtoReflect.Descriptor instead.
func (*StartCommand) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{6}
}

func (x *StartCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StartCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StartCommand) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type ExecInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecInput_Start
	//	*ExecInput_Stdin
	//	*ExecInput_CloseStdin
	Payload       isExecInput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_homectl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{7}
}

func (x *ExecInput) GetPayload() isExecInput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecInput) GetStart() *StartCommand {
	if x != nil {
		if x, ok := x.Payload.(*ExecInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecInput) GetCloseStdin() bool {
	if x != nil {
		if x, ok := x.Payload.(*ExecInput_CloseStdin); ok {
			return x.CloseStdin
		}
	}
	return false
}

type isExecInput_Payload interface {
	isExecInput_Payload()
}

type ExecInput_Start struct {
	Start *StartCommand `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecInput_CloseStdin struct {
	CloseStdin bool `protobuf:"varint,3,opt,name=close_stdin,json=closeStdin,proto3,oneof"`
}

func (*ExecInput_Start) isExecInput_Payload() {}

func (*ExecInput_Stdin) isExecInput_Payload() {}

func (*ExecInput_CloseStdin) isExecInput_Payload() {}

type ExecOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecOutput_Stdout
	//	*ExecOutput_Stderr
	//	*ExecOutput_Exit
	Payload       isExecOutput_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_homectl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{8}
}

func (x *ExecOutput) GetPayload() isExecOutput_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecOutput) GetExit() *ExitStatus {
	if x != nil {
		if x, ok := x.Payload.(*ExecOutput_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecOutput_Payload interface {
	isExecOutput_Payload()
}

type ExecOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecOutput_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecOutput_Exit struct {
	Exit *ExitStatus `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecOutput_Stdout) isExecOutput_Payload() {}

func (*ExecOutput_Stderr) isExecOutput_Payload() {}

func (*ExecOutput_Exit) isExecOutput_Payload() {}

type ExitStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitStatus) Reset() {
	*x = ExitStatus{}
	mi := &file_homectl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitStatus) ProtoMessage() {}

func (x *ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitStatus.ProtoReflect.Descriptor instead.
func (*ExitStatus) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{9}
}

func (x *ExitStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExitStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UploadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadChunk_DestinationPath
	//	*UploadChunk_Data
	Payload       isUploadChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_homectl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{10}
}

func (x *UploadChunk) GetPayload() isUploadChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadChunk) GetDestinationPath() string {
	if x != nil {
		if x, ok := x.Payload.(*UploadChunk_DestinationPath); ok {
			return x.DestinationPath
		}
	}
	return ""
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUploadChunk_Payload interface {
	isUploadChunk_Payload()
}

type UploadChunk_DestinationPath struct {
	DestinationPath string `protobuf:"bytes,1,opt,name=destination_path,json=destinationPath,proto3,oneof"`
}

type UploadChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UploadChunk_DestinationPath) isUploadChunk_Payload() {}

func (*UploadChunk_Data) isUploadChunk_Payload() {}

type UploadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  uint64                 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSummary) Reset() {
	*x = UploadSummary{}
	mi := &file_homectl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSummary) ProtoMessage() {}

func (x *UploadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSummary.ProtoReflect.Descriptor instead.
func (*UploadSummary) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{11}
}

func (x *UploadSummary) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *UploadSummary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_homectl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_homectl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{13}
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_homectl_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{14}
}

type ServiceUnit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "nginx.service"
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LoadState     string                 `protobuf:"bytes,3,opt,name=load_state,json=loadState,proto3" json:"load_state,omitempty"`               // loaded, not-found, masked...
	ActiveState   string                 `protobuf:"bytes,4,opt,name=active_state,json=activeState,proto3" json:"active_state,omitempty"`         // active, inactive, failed, activating...
	SubState      string                 `protobuf:"bytes,5,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`                  // running, dead, exited...
	UnitFileState string                 `protobuf:"bytes,6,opt,name=unit_file_state,json=unitFileState,proto3" json:"unit_file_state,omitempty"` // enabled, disabled, static, masked...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUnit) Reset() {
	*x = ServiceUnit{}
	mi := &file_homectl_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUnit) ProtoMessage() {}

func (x *ServiceUnit) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUnit.ProtoReflect.Descriptor instead.
func (*ServiceUnit) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{15}
}

func (x *ServiceUnit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceUnit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceUnit) GetLoadState() string {
	if x != nil {
		return x.LoadState
	}
	return ""
}

func (x *ServiceUnit) GetActiveState() string {
	if x != nil {
		return x.ActiveState
	}
	return ""
}

func (x *ServiceUnit) GetSubState() string {
	if x != nil {
		return x.SubState
	}
	return ""
}

func (x *ServiceUnit) GetUnitFileState() string {
	if x != nil {
		return x.UnitFileState
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceUnit         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_homectl_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{16}
}

func (x *ListServicesResponse) GetServices() []*ServiceUnit {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Action        ServiceActionType      `protobuf:"varint,2,opt,name=action,proto3,enum=homectl.v1.ServiceActionType" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActionRequest) Reset() {
	*x = ServiceActionRequest{}
	mi := &file_homectl_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActionRequest) ProtoMessage() {}

func (x *ServiceActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActionRequest.ProtoReflect.Descriptor instead.
func (*ServiceActionRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceActionRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *ServiceActionRequest) GetAction() ServiceActionType {
	if x != nil {
		return x.Action
	}
	return ServiceActionType_SERVICE_ACTION_UNSPECIFIED
}

type ServiceActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // combined systemctl output, useful on failure
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceActionResponse) Reset() {
	*x = ServiceActionResponse{}
	mi := &file_homectl_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceActionResponse) ProtoMessage() {}

func (x *ServiceActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceActionResponse.ProtoReflect.Descriptor instead.
func (*ServiceActionResponse) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{18}
}

func (x *ServiceActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TailLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsRequest) Reset() {
	*x = TailLogsRequest{}
	mi := &file_homectl_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsRequest) ProtoMessage() {}

func (x *TailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsRequest.ProtoReflect.Descriptor instead.
func (*TailLogsRequest) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{19}
}

func (x *TailLogsRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_homectl_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_homectl_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_homectl_proto_rawDescGZIP(), []int{20}
}

func (x *LogLine) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_homectl_proto protoreflect.FileDescriptor

const file_homectl_proto_rawDesc = "" +
	"\n" +
	"\rhomectl.proto\x12\n" +
	"homectl.v1\"\x14\n" +
	"\x12FingerprintRequest\"7\n" +
	"\x13FingerprintResponse\x12 \n" +
	"\vfingerprint\x18\x01 \x01(\tR\vfingerprint\".\n" +
	"\vPairRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\"s\n" +
	"\fPairResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12-\n" +
	"\x12daemon_fingerprint\x18\x02 \x01(\tR\x11daemonFingerprint\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x13\n" +
	"\x11SystemInfoRequest\"\x98\x03\n" +
	"\x12SystemInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12)\n" +
	"\x10platform_version\x18\x03 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x04R\ruptimeSeconds\x12\x1b\n" +
	"\tcpu_model\x18\x05 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_cores\x18\x06 \x01(\rR\bcpuCores\x12*\n" +
	"\x11cpu_usage_percent\x18\a \x01(\x01R\x0fcpuUsagePercent\x12&\n" +
	"\x0fmem_total_bytes\x18\b \x01(\x04R\rmemTotalBytes\x12$\n" +
	"\x0emem_used_bytes\x18\t \x01(\x04R\fmemUsedBytes\x12(\n" +
	"\x10disk_total_bytes\x18\n" +
	" \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\v \x01(\x04R\rdiskUsedBytes\"]\n" +
	"\fStartCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vworking_dir\x18\x03 \x01(\tR\n" +
	"workingDir\"\x83\x01\n" +
	"\tExecInput\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x18.homectl.v1.StartCommandH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12!\n" +
	"\vclose_stdin\x18\x03 \x01(\bH\x00R\n" +
	"closeStdinB\t\n" +
	"\apayload\"y\n" +
	"\n" +
	"ExecOutput\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12,\n" +
	"\x04exit\x18\x03 \x01(\v2\x16.homectl.v1.ExitStatusH\x00R\x04exitB\t\n" +
	"\apayload\"6\n" +
	"\n" +
	"ExitStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"[\n" +
	"\vUploadChunk\x12+\n" +
	"\x10destination_path\x18\x01 \x01(\tH\x00R\x0fdestinationPath\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"H\n" +
	"\rUploadSummary\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x04R\fbytesWritten\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"%\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"#\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x15\n" +
	"\x13ListServicesRequest\"\xca\x01\n" +
	"\vServiceUnit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"load_state\x18\x03 \x01(\tR\tloadState\x12!\n" +
	"\factive_state\x18\x04 \x01(\tR\vactiveState\x12\x1b\n" +
	"\tsub_state\x18\x05 \x01(\tR\bsubState\x12&\n" +
	"\x0funit_file_state\x18\x06 \x01(\tR\runitFileState\"K\n" +
	"\x14ListServicesResponse\x123\n" +
	"\bservices\x18\x01 \x03(\v2\x17.homectl.v1.ServiceUnitR\bservices\"a\n" +
	"\x14ServiceActionRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x125\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1d.homectl.v1.ServiceActionTypeR\x06action\"K\n" +
	"\x15ServiceActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\x0fTailLogsRequest\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\"\x1d\n" +
	"\aLogLine\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text*\xb9\x01\n" +
	"\x11ServiceActionType\x12\x1e\n" +
	"\x1aSERVICE_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SERVICE_ACTION_START\x10\x01\x12\x17\n" +
	"\x13SERVICE_ACTION_STOP\x10\x02\x12\x1a\n" +
	"\x16SERVICE_ACTION_RESTART\x10\x03\x12\x19\n" +
	"\x15SERVICE_ACTION_ENABLE\x10\x04\x12\x1a\n" +
	"\x16SERVICE_ACTION_DISABLE\x10\x052\x9e\x01\n" +
	"\x0ePairingService\x12Q\n" +
	"\x0eGetFingerprint\x12\x1e.homectl.v1.FingerprintRequest\x1a\x1f.homectl.v1.FingerprintResponse\x129\n" +
	"\x04Pair\x12\x17.homectl.v1.PairRequest\x1a\x18.homectl.v1.PairResponse2\x87\x04\n" +
	"\x0eHomectlService\x12K\n" +
	"\n" +
	"SystemInfo\x12\x1d.homectl.v1.SystemInfoRequest\x1a\x1e.homectl.v1.SystemInfoResponse\x129\n" +
	"\x04Exec\x12\x15.homectl.v1.ExecInput\x1a\x16.homectl.v1.ExecOutput(\x010\x01\x12>\n" +
	"\x06Upload\x12\x17.homectl.v1.UploadChunk\x1a\x19.homectl.v1.UploadSummary(\x01\x12D\n" +
	"\bDownload\x12\x1b.homectl.v1.DownloadRequest\x1a\x19.homectl.v1.DownloadChunk0\x01\x12Q\n" +
	"\fListServices\x12\x1f.homectl.v1.ListServicesRequest\x1a .homectl.v1.ListServicesResponse\x12T\n" +
	"\rServiceAction\x12 .homectl.v1.ServiceActionRequest\x1a!.homectl.v1.ServiceActionResponse\x12>\n" +
	"\bTailLogs\x12\x1b.homectl.v1.TailLogsRequest\x1a\x13.homectl.v1.LogLine0\x01B\x1fZ\x1dhomectl/internal/shared/pb;pbb\x06proto3"

var (
	file_homectl_proto_rawDescOnce sync.Once
	file_homectl_proto_rawDescData []byte
)

func file_homectl_proto_rawDescGZIP() []byte {
	file_homectl_proto_rawDescOnce.Do(func() {
		file_homectl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_homectl_proto_rawDesc), len(file_homectl_proto_rawDesc)))
	})
	return file_homectl_proto_rawDescData
}

var file_homectl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_homectl_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_homectl_proto_goTypes = []any{
	(ServiceActionType)(0),        // 0: homectl.v1.ServiceActionType
	(*FingerprintRequest)(nil),    // 1: homectl.v1.FingerprintRequest
	(*FingerprintResponse)(nil),   // 2: homectl.v1.FingerprintResponse
	(*PairRequest)(nil),           // 3: homectl.v1.PairRequest
	(*PairResponse)(nil),          // 4: homectl.v1.PairResponse
	(*SystemInfoRequest)(nil),     // 5: homectl.v1.SystemInfoRequest
	(*SystemInfoResponse)(nil),    // 6: homectl.v1.SystemInfoResponse
	(*StartCommand)(nil),          // 7: homectl.v1.StartCommand
	(*ExecInput)(nil),             // 8: homectl.v1.ExecInput
	(*ExecOutput)(nil),            // 9: homectl.v1.ExecOutput
	(*ExitStatus)(nil),            // 10: homectl.v1.ExitStatus
	(*UploadChunk)(nil),           // 11: homectl.v1.UploadChunk
	(*UploadSummary)(nil),         // 12: homectl.v1.UploadSummary
	(*DownloadRequest)(nil),       // 13: homectl.v1.DownloadRequest
	(*DownloadChunk)(nil),         // 14: homectl.v1.DownloadChunk
	(*ListServicesRequest)(nil),   // 15: homectl.v1.ListServicesRequest
	(*ServiceUnit)(nil),           // 16: homectl.v1.ServiceUnit
	(*ListServicesResponse)(nil),  // 17: homectl.v1.ListServicesResponse
	(*ServiceActionRequest)(nil),  // 18: homectl.v1.ServiceActionRequest
	(*ServiceActionResponse)(nil), // 19: homectl.v1.ServiceActionResponse
	(*TailLogsRequest)(nil),       // 20: homectl.v1.TailLogsRequest
	(*LogLine)(nil),               // 21: homectl.v1.LogLine
}
var file_homectl_proto_depIdxs = []int32{
	7,  // 0: homectl.v1.ExecInput.start:type_name -> homectl.v1.StartCommand
	10, // 1: homectl.v1.ExecOutput.exit:type_name -> homectl.v1.ExitStatus
	16, // 2: homectl.v1.ListServicesResponse.services:type_name -> homectl.v1.ServiceUnit
	0,  // 3: homectl.v1.ServiceActionRequest.action:type_name -> homectl.v1.ServiceActionType
	1,  // 4: homectl.v1.PairingService.GetFingerprint:input_type -> homectl.v1.FingerprintRequest
	3,  // 5: homectl.v1.PairingService.Pair:input_type -> homectl.v1.PairRequest
	5,  // 6: homectl.v1.HomectlService.SystemInfo:input_type -> homectl.v1.SystemInfoRequest
	8,  // 7: homectl.v1.HomectlService.Exec:input_type -> homectl.v1.ExecInput
	11, // 8: homectl.v1.HomectlService.Upload:input_type -> homectl.v1.UploadChunk
	13, // 9: homectl.v1.HomectlService.Download:input_type -> homectl.v1.DownloadRequest
	15, // 10: homectl.v1.HomectlService.ListServices:input_type -> homectl.v1.ListServicesRequest
	18, // 11: homectl.v1.HomectlService.ServiceAction:input_type -> homectl.v1.ServiceActionRequest
	20, // 12: homectl.v1.HomectlService.TailLogs:input_type -> homectl.v1.TailLogsRequest
	2,  // 13: homectl.v1.PairingService.GetFingerprint:output_type -> homectl.v1.FingerprintResponse
	4,  // 14: homectl.v1.PairingService.Pair:output_type -> homectl.v1.PairResponse
	6,  // 15: homectl.v1.HomectlService.SystemInfo:output_type -> homectl.v1.SystemInfoResponse
	9,  // 16: homectl.v1.HomectlService.Exec:output_type -> homectl.v1.ExecOutput
	12, // 17: homectl.v1.HomectlService.Upload:output_type -> homectl.v1.UploadSummary
	14, // 18: homectl.v1.HomectlService.Download:output_type -> homectl.v1.DownloadChunk
	17, // 19: homectl.v1.HomectlService.ListServices:output_type -> homectl.v1.ListServicesResponse
	19, // 20: homectl.v1.HomectlService.ServiceAction:output_type -> homectl.v1.ServiceActionResponse
	21, // 21: homectl.v1.HomectlService.TailLogs:output_type -> homectl.v1.LogLine
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_homectl_proto_init() }
func file_homectl_proto_init() {
	if File_homectl_proto != nil {
		return
	}
	file_homectl_proto_msgTypes[7].OneofWrappers = []any{
		(*ExecInput_Start)(nil),
		(*ExecInput_Stdin)(nil),
		(*ExecInput_CloseStdin)(nil),
	}
	file_homectl_proto_msgTypes[8].OneofWrappers = []any{
		(*ExecOutput_Stdout)(nil),
		(*ExecOutput_Stderr)(nil),
		(*ExecOutput_Exit)(nil),
	}
	file_homectl_proto_msgTypes[10].OneofWrappers = []any{
		(*UploadChunk_DestinationPath)(nil),
		(*UploadChunk_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_homectl_proto_rawDesc), len(file_homectl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_homectl_proto_goTypes,
		DependencyIndexes: file_homectl_proto_depIdxs,
		EnumInfos:         file_homectl_proto_enumTypes,
		MessageInfos:      file_homectl_proto_msgTypes,
	}.Build()
	File_homectl_proto = out.File
	file_homectl_proto_goTypes = nil
	file_homectl_proto_depIdxs = nil
}
