// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: homectl.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PairingService_GetFingerprint_FullMethodName = "/homectl.v1.PairingService/GetFingerprint"
	PairingService_Pair_FullMethodName           = "/homectl.v1.PairingService/Pair"
)

// PairingServiceClient is the client API for PairingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PairingService is exempt from the "pinned client certificate" check in the
// daemon's auth interceptor. It still requires a full mTLS handshake (the
// client always presents a certificate), but the daemon does not require
// that certificate's fingerprint to already be trusted. Pair() itself only
// succeeds while the daemon's pairing window is open (see internal/daemon/pairing).
type PairingServiceClient interface {
	// GetFingerprint returns the daemon's own identity fingerprint, mostly
	// useful for CLI/debugging cross-checks; clients should primarily derive
	// the daemon fingerprint from the TLS certificate presented during the
	// handshake itself, not from this RPC response.
	GetFingerprint(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (*FingerprintResponse, error)
	// Pair registers the caller's TLS client certificate fingerprint as
	// trusted, if and only if the daemon's pairing window is currently open.
	Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*PairResponse, error)
}

type pairingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPairingServiceClient(cc grpc.ClientConnInterface) PairingServiceClient {
	return &pairingServiceClient{cc}
}

func (c *pairingServiceClient) GetFingerprint(ctx context.Context, in *FingerprintRequest, opts ...grpc.CallOption) (*FingerprintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FingerprintResponse)
	err := c.cc.Invoke(ctx, PairingService_GetFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pairingServiceClient) Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*PairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairResponse)
	err := c.cc.Invoke(ctx, PairingService_Pair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PairingServiceServer is the server API for PairingService service.
// All implementations must embed UnimplementedPairingServiceServer
// for forward compatibility.
//
// PairingService is exempt from the "pinned client certificate" check in the
// daemon's auth interceptor. It still requires a full mTLS handshake (the
// client always presents a certificate), but the daemon does not require
// that certificate's fingerprint to already be trusted. Pair() itself only
// succeeds while the daemon's pairing window is open (see internal/daemon/pairing).
type PairingServiceServer interface {
	// GetFingerprint returns the daemon's own identity fingerprint, mostly
	// useful for CLI/debugging cross-checks; clients should primarily derive
	// the daemon fingerprint from the TLS certificate presented during the
	// handshake itself, not from this RPC response.
	GetFingerprint(context.Context, *FingerprintRequest) (*FingerprintResponse, error)
	// Pair registers the caller's TLS client certificate fingerprint as
	// trusted, if and only if the daemon's pairing window is currently open.
	Pair(context.Context, *PairRequest) (*PairResponse, error)
	mustEmbedUnimplementedPairingServiceServer()
}

// UnimplementedPairingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPairingServiceServer struct{}

func (UnimplementedPairingServiceServer) GetFingerprint(context.Context, *FingerprintRequest) (*FingerprintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFingerprint not implemented")
}
func (UnimplementedPairingServiceServer) Pair(context.Context, *PairRequest) (*PairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Pair not implemented")
}
func (UnimplementedPairingServiceServer) mustEmbedUnimplementedPairingServiceServer() {}
func (UnimplementedPairingServiceServer) testEmbeddedByValue()                        {}

// UnsafePairingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PairingServiceServer will
// result in compilation errors.
type UnsafePairingServiceServer interface {
	mustEmbedUnimplementedPairingServiceServer()
}

func RegisterPairingServiceServer(s grpc.ServiceRegistrar, srv PairingServiceServer) {
	// If the following call panics, it indicates UnimplementedPairingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PairingService_ServiceDesc, srv)
}

func _PairingService_GetFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServiceServer).GetFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PairingService_GetFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServiceServer).GetFingerprint(ctx, req.(*FingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PairingService_Pair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServiceServer).Pair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PairingService_Pair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServiceServer).Pair(ctx, req.(*PairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PairingService_ServiceDesc is the grpc.ServiceDesc for PairingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PairingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "homectl.v1.PairingService",
	HandlerType: (*PairingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFingerprint",
			Handler:    _PairingService_GetFingerprint_Handler,
		},
		{
			MethodName: "Pair",
			Handler:    _PairingService_Pair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "homectl.proto",
}

const (
	HomectlService_SystemInfo_FullMethodName    = "/homectl.v1.HomectlService/SystemInfo"
	HomectlService_Exec_FullMethodName          = "/homectl.v1.HomectlService/Exec"
	HomectlService_Upload_FullMethodName        = "/homectl.v1.HomectlService/Upload"
	HomectlService_Download_FullMethodName      = "/homectl.v1.HomectlService/Download"
	HomectlService_ListServices_FullMethodName  = "/homectl.v1.HomectlService/ListServices"
	HomectlService_ServiceAction_FullMethodName = "/homectl.v1.HomectlService/ServiceAction"
	HomectlService_TailLogs_FullMethodName      = "/homectl.v1.HomectlService/TailLogs"
)

// HomectlServiceClient is the client API for HomectlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HomectlService requires an already-pinned client certificate (established
// via a prior successful PairingService.Pair call).
type HomectlServiceClient interface {
	SystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error)
	// Exec is bidirectional: the first ExecInput must carry a StartCommand;
	// subsequent ExecInput messages may carry stdin chunks. The server streams
	// back stdout/stderr chunks, terminated by one ExitStatus message.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error)
	// Upload is client-streaming: the first UploadChunk must carry the
	// destination path; subsequent chunks carry raw file data.
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadSummary], error)
	// Download is server-streaming: the daemon reads the requested path and
	// streams it back as a sequence of DownloadChunk messages.
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadChunk], error)
	// ListServices lists systemd service units and their current state.
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// ServiceAction starts, stops, restarts, enables, or disables a single
	// systemd service unit.
	ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error)
	// TailLogs streams `journalctl -u <unit> -f` output for a single systemd
	// service unit, one line per message, until the caller disconnects.
	TailLogs(ctx context.Context, in *TailLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
}

type homectlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHomectlServiceClient(cc grpc.ClientConnInterface) HomectlServiceClient {
	return &homectlServiceClient{cc}
}

func (c *homectlServiceClient) SystemInfo(ctx context.Context, in *SystemInfoRequest, opts ...grpc.CallOption) (*SystemInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemInfoResponse)
	err := c.cc.Invoke(ctx, HomectlService_SystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homectlServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecInput, ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HomectlService_ServiceDesc.Streams[0], HomectlService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecInput, ExecOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_ExecClient = grpc.BidiStreamingClient[ExecInput, ExecOutput]

func (c *homectlServiceClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadChunk, UploadSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HomectlService_ServiceDesc.Streams[1], HomectlService_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadChunk, UploadSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_UploadClient = grpc.ClientStreamingClient[UploadChunk, UploadSummary]

func (c *homectlServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HomectlService_ServiceDesc.Streams[2], HomectlService_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, DownloadChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_DownloadClient = grpc.ServerStreamingClient[DownloadChunk]

func (c *homectlServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, HomectlService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homectlServiceClient) ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceActionResponse)
	err := c.cc.Invoke(ctx, HomectlService_ServiceAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homectlServiceClient) TailLogs(ctx context.Context, in *TailLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HomectlService_ServiceDesc.Streams[3], HomectlService_TailLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TailLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_TailLogsClient = grpc.ServerStreamingClient[LogLine]

// HomectlServiceServer is the server API for HomectlService service.
// All implementations must embed UnimplementedHomectlServiceServer
// for forward compatibility.
//
// HomectlService requires an already-pinned client certificate (established
// via a prior successful PairingService.Pair call).
type HomectlServiceServer interface {
	SystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error)
	// Exec is bidirectional: the first ExecInput must carry a StartCommand;
	// subsequent ExecInput messages may carry stdin chunks. The server streams
	// back stdout/stderr chunks, terminated by one ExitStatus message.
	Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error
	// Upload is client-streaming: the first UploadChunk must carry the
	// destination path; subsequent chunks carry raw file data.
	Upload(grpc.ClientStreamingServer[UploadChunk, UploadSummary]) error
	// Download is server-streaming: the daemon reads the requested path and
	// streams it back as a sequence of DownloadChunk messages.
	Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadChunk]) error
	// ListServices lists systemd service units and their current state.
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// ServiceAction starts, stops, restarts, enables, or disables a single
	// systemd service unit.
	ServiceAction(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error)
	// TailLogs streams `journalctl -u <unit> -f` output for a single systemd
	// service unit, one line per message, until the caller disconnects.
	TailLogs(*TailLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	mustEmbedUnimplementedHomectlServiceServer()
}

// UnimplementedHomectlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHomectlServiceServer struct{}

func (UnimplementedHomectlServiceServer) SystemInfo(context.Context, *SystemInfoRequest) (*SystemInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemInfo not implemented")
}
func (UnimplementedHomectlServiceServer) Exec(grpc.BidiStreamingServer[ExecInput, ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedHomectlServiceServer) Upload(grpc.ClientStreamingServer[UploadChunk, UploadSummary]) error {
	return status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedHomectlServiceServer) Download(*DownloadRequest, grpc.ServerStreamingServer[DownloadChunk]) error {
	return status.Error(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedHomectlServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedHomectlServiceServer) ServiceAction(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServiceAction not implemented")
}
func (UnimplementedHomectlServiceServer) TailLogs(*TailLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method TailLogs not implemented")
}
func (UnimplementedHomectlServiceServer) mustEmbedUnimplementedHomectlServiceServer() {}
func (UnimplementedHomectlServiceServer) testEmbeddedByValue()                        {}

// UnsafeHomectlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomectlServiceServer will
// result in compilation errors.
type UnsafeHomectlServiceServer interface {
	mustEmbedUnimplementedHomectlServiceServer()
}

func RegisterHomectlServiceServer(s grpc.ServiceRegistrar, srv HomectlServiceServer) {
	// If the following call panics, it indicates UnimplementedHomectlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HomectlService_ServiceDesc, srv)
}

func _HomectlService_SystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomectlServiceServer).SystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomectlService_SystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomectlServiceServer).SystemInfo(ctx, req.(*SystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomectlService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HomectlServiceServer).Exec(&grpc.GenericServerStream[ExecInput, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_ExecServer = grpc.BidiStreamingServer[ExecInput, ExecOutput]

func _HomectlService_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HomectlServiceServer).Upload(&grpc.GenericServerStream[UploadChunk, UploadSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_UploadServer = grpc.ClientStreamingServer[UploadChunk, UploadSummary]

func _HomectlService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HomectlServiceServer).Download(m, &grpc.GenericServerStream[DownloadRequest, DownloadChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_DownloadServer = grpc.ServerStreamingServer[DownloadChunk]

func _HomectlService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomectlServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomectlService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomectlServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomectlService_ServiceAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomectlServiceServer).ServiceAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomectlService_ServiceAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomectlServiceServer).ServiceAction(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomectlService_TailLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TailLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HomectlServiceServer).TailLogs(m, &grpc.GenericServerStream[TailLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HomectlService_TailLogsServer = grpc.ServerStreamingServer[LogLine]

// HomectlService_ServiceDesc is the grpc.ServiceDesc for HomectlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HomectlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "homectl.v1.HomectlService",
	HandlerType: (*HomectlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SystemInfo",
			Handler:    _HomectlService_SystemInfo_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _HomectlService_ListServices_Handler,
		},
		{
			MethodName: "ServiceAction",
			Handler:    _HomectlService_ServiceAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _HomectlService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Upload",
			Handler:       _HomectlService_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _HomectlService_Download_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TailLogs",
			Handler:       _HomectlService_TailLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "homectl.proto",
}
